######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 9 21:20:03 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

include(libs/qwt/src/qwt.pri)
include(libs/qextserialport/src/qextserialport.pri)

# Input
HEADERS += ProgramGuiWindow.h
SOURCES += ProgramGuiWindow.cpp PulseGeneratorGui.cpp
