######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 9 21:20:03 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += BasicPulseTrainWindow.h
SOURCES += BasicPulseTrainWindow.cpp PulseGeneratorGui.cpp
